### ISSUE TITLE
Monitor cannot differentiate between network error or no POIs around the user

### ISSUE THREAD

**Issue by iewilliam** [adobe/places-monitor-ios#21]
### Expected Behaviour
Monitor extension should not deregister previously registered geofences if we failed to fetch new list of POIs due to network error

### Actual Behaviour
The current POI fetch API does not return any error code. If it returns no POIs, monitor automatically deregistered all monitored geofences.

### Reproduce Scenario (including but not limited to)
Have the monitor running and tracking POIs. turn off network, move a significant distance. All tracked POIs will now be deregistered.

**Comment by sbenedicadb** [comment]
the Places Extension has been updated with a new API to allow us to differentiate now.  need to take this task up and bump min version of Places Extension dependency to 1.1.0

**Comment by sbenedicadb** [comment]
released in 2.0.0
