### ISSUE TITLE
Found a problem when we install nested dependency by Cocoapods

### ISSUE THREAD

**Issue by chawatvish** [adobe/places-monitor-ios#44]
Dear all,
We found a problem we can't build your lib when we use it on nested dependency.
It showed `ACPCore.h`, `ACPExtensionEvent.h` etc. not found.
And that we solved this issue by using import lib with namespace syntax.
So, we try to change your code on Cocoapods and it works!.
Actually, I would like to open a pull request but your rule makes me create an issue first. 🤔

Please review this issue because we are blocked.

Ref: [https://github.com/chawatvish/places-monitor-ios/commit/ed7e4fae1b8be5865cdd22828ca0d71302098b72](url)

**Comment by chawatvish** [comment]
Please check out this link for more information about Multiple Xcodeproj Generation.
http://blog.cocoapods.org/CocoaPods-1.7.0-beta/

**Comment by sbenedicadb** [comment]
fixed in release 2.1.1.  thanks @chawatvish!
